### ISSUE TITLE
Parser should fail when a string contains invalid unicode escapes

### ISSUE THREAD

**Issue by benjreinhart** [kdl-org/kdljs#10]
If I'm reading the grammar right, an invalid unicode escape should cause the parser to fail. The below examples fail parsing in the rust implementation.

Grammar from spec:

```
character := '\' escape | [^\"]
escape := ["\\/bfnrt] | 'u{' hex-digit{1, 6} '}'
```

#### Existing behavior

```js
// Not in 1..6 digits
kdl.parse("node \"\\u{}\"").output[0]
// { name: 'node', properties: {}, values: [ 'u{}' ], children: [] }

// Invalid hex digit(s)
kdl.parse("node \"\\u{xyz}\"").output[0]
// { name: 'node', properties: {}, values: [ 'u{xyz}' ], children: [] }

// Outside range 0..0x10FFFF
kdl.parse("node \"\\u{11FFFF}\"").output[0]
// { name: 'node', properties: {}, values: [ '￿' ], children: [] }

// Unterminated unicode escape
kdl.parse("node \"\\u{\"").output[0]
// { name: 'node', properties: {}, values: [ 'u{' ], children: [] }

// Not in 1..6 digits
kdl.parse("node \"\\u{1234567}\"").output[0]
// { name: 'node', properties: {}, values: [ 'u{1234567}' ], children: [] }
```

#### Expected behavior

I would expect each of the above examples to fail to parse.

**Comment by larsgw** [comment]
Thank you for the report. The third example is something I need to fix but the rest should be caught by tokenization, I would think. AFAIK, it doesn't accept loose backslashes or invalid escapes (again, apart from `0x10FFFF..0xFFFFFF`). I will check out what's going on there.

**Comment by larsgw** [comment]
It *is* being caught by the lexer but the rest of the function doesn't do anything with the error and just parses the tokens up to the error. This goes for #11 as well. A fix would be to check the output in the line below. I don't have time for this the next few days though.

https://github.com/kdl-org/kdljs/blob/c94f5c8b648f8e2971d1c54b532abb9c32bef0a5/src/parser/kdl.js#L307

**Comment by benjreinhart** [comment]
>  I don't have time for this the next few days though.

No worries and no rush! FWIW I'm trying to write an elixir implementation for fun / learning and in doing so I am using this and the Rust implementation as my sanity checks when I find behavior I'm unsure of, hence the issues. So no pressure on any fixes, I just want to give a heads up and document anything suspicious.

If I have some time, I'll try to take a peak at this as well to hopefully contribute more than just issues.
