### ISSUE TITLE
KDL 1.0 Compliance

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdljs#6]
Hi! Since this was originally written, KDL has stabilized to 1.0.0. No further changes should be made to spec so it should be safe to update + finalize kdljs to the 1.0 spec!

Please let me know if you have any questions or if there's anything I can do to help!

**Comment by larsgw** [comment]
I still wonder whether I should change the parser output to better support value tags, and in the future the query spec. Right now it's just a bunch of objects. Node tags could be another property, value tags could be handled based on user-supplied callbacks (or opt-in defaults) and queries could be loose functions taking the document as an argument. But I could also make classes.

**Comment by zkat** [comment]
I mean I think as long as you're _parsing_ the spec, it's fine to throw away tags, in general? Though for kdljs itself it might be good to just shove that metadata into a `type` property?

**Comment by larsgw** [comment]
Maybe `valueOf()` is good enough to just change to classes and have the API be almost the same? Like, would `new Value(10) + 2` work? I haven't used it that much before and maybe it'd just be weird. I guess typeof breaks (or does it use `valueOf` too?)

**Comment by larsgw** [comment]
How would that look then?

```js
{
  node: 'foo',
  values: [1, 2],
  properties: { foo: 'bar' },
  type: {
    name: 'node-tag',
    values: [null, 'i32'],
    properties: { foo: 'url' }
  }
}
```

**Comment by zkat** [comment]
that doesn't look too shabby if you're willing to expose your guts.

It might be nice for kdljs to start supporting stuff through queries, though? And just plain methods instead of just giving you a whole structure?

**Comment by larsgw** [comment]
I released `v0.1.0` for now with parsing compliance, I'll deal with query, schema and tag support later.

**Comment by larsgw** [comment]
(`v0.1.1` now because I messed up the formatter)

**Comment by zkat** [comment]
I think that's good enough for me if you want to close this issue! The other stuff can come later :)
